# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/main/resources/tokenize.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
  _runtime_version.Domain.PUBLIC,
  5,
  27,
  1,
  '',
  'src/main/resources/tokenize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!src/main/resources/tokenize.proto\x12\x11tokenizeSerialize\"\x18\n\x08TextList\x12\x0c\n\x04text\x18\x01 \x03(\t\"\x18\n\x06Tokens\x12\x0e\n\x06tokens\x18\x01 \x03(\x05\"4\n\tTokenList\x12\'\n\x04list\x18\x01 \x03(\x0b\x32\x19.tokenizeSerialize.TokensB\x0f\n\rphi3zh.commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.main.resources.tokenize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rphi3zh.common'
  _globals['_TEXTLIST']._serialized_start=56
  _globals['_TEXTLIST']._serialized_end=80
  _globals['_TOKENS']._serialized_start=82
  _globals['_TOKENS']._serialized_end=106
  _globals['_TOKENLIST']._serialized_start=108
  _globals['_TOKENLIST']._serialized_end=160
# @@protoc_insertion_point(module_scope)
