// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/tokenize.proto
// Protobuf Java Version: 4.27.1

package phi3zh.common;

public final class Tokenize {
  private Tokenize() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      Tokenize.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tokenizeSerialize.TextList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string text = 1;</code>
     * @return A list containing the text.
     */
    java.util.List<java.lang.String>
        getTextList();
    /**
     * <code>repeated string text = 1;</code>
     * @return The count of text.
     */
    int getTextCount();
    /**
     * <code>repeated string text = 1;</code>
     * @param index The index of the element to return.
     * @return The text at the given index.
     */
    java.lang.String getText(int index);
    /**
     * <code>repeated string text = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the text at the given index.
     */
    com.google.protobuf.ByteString
        getTextBytes(int index);
  }
  /**
   * Protobuf type {@code tokenizeSerialize.TextList}
   */
  public static final class TextList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tokenizeSerialize.TextList)
      TextListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        TextList.class.getName());
    }
    // Use TextList.newBuilder() to construct.
    private TextList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TextList() {
      text_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TextList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TextList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              phi3zh.common.Tokenize.TextList.class, phi3zh.common.Tokenize.TextList.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList text_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string text = 1;</code>
     * @return A list containing the text.
     */
    public com.google.protobuf.ProtocolStringList
        getTextList() {
      return text_;
    }
    /**
     * <code>repeated string text = 1;</code>
     * @return The count of text.
     */
    public int getTextCount() {
      return text_.size();
    }
    /**
     * <code>repeated string text = 1;</code>
     * @param index The index of the element to return.
     * @return The text at the given index.
     */
    public java.lang.String getText(int index) {
      return text_.get(index);
    }
    /**
     * <code>repeated string text = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the text at the given index.
     */
    public com.google.protobuf.ByteString
        getTextBytes(int index) {
      return text_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < text_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, text_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < text_.size(); i++) {
          dataSize += computeStringSizeNoTag(text_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTextList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof phi3zh.common.Tokenize.TextList)) {
        return super.equals(obj);
      }
      phi3zh.common.Tokenize.TextList other = (phi3zh.common.Tokenize.TextList) obj;

      if (!getTextList()
          .equals(other.getTextList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTextCount() > 0) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getTextList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static phi3zh.common.Tokenize.TextList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phi3zh.common.Tokenize.TextList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.TextList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phi3zh.common.Tokenize.TextList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.TextList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phi3zh.common.Tokenize.TextList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.TextList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static phi3zh.common.Tokenize.TextList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static phi3zh.common.Tokenize.TextList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static phi3zh.common.Tokenize.TextList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.TextList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static phi3zh.common.Tokenize.TextList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(phi3zh.common.Tokenize.TextList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tokenizeSerialize.TextList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tokenizeSerialize.TextList)
        phi3zh.common.Tokenize.TextListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TextList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TextList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                phi3zh.common.Tokenize.TextList.class, phi3zh.common.Tokenize.TextList.Builder.class);
      }

      // Construct using phi3zh.common.Tokenize.TextList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        text_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TextList_descriptor;
      }

      @java.lang.Override
      public phi3zh.common.Tokenize.TextList getDefaultInstanceForType() {
        return phi3zh.common.Tokenize.TextList.getDefaultInstance();
      }

      @java.lang.Override
      public phi3zh.common.Tokenize.TextList build() {
        phi3zh.common.Tokenize.TextList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public phi3zh.common.Tokenize.TextList buildPartial() {
        phi3zh.common.Tokenize.TextList result = new phi3zh.common.Tokenize.TextList(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(phi3zh.common.Tokenize.TextList result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          text_.makeImmutable();
          result.text_ = text_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof phi3zh.common.Tokenize.TextList) {
          return mergeFrom((phi3zh.common.Tokenize.TextList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(phi3zh.common.Tokenize.TextList other) {
        if (other == phi3zh.common.Tokenize.TextList.getDefaultInstance()) return this;
        if (!other.text_.isEmpty()) {
          if (text_.isEmpty()) {
            text_ = other.text_;
            bitField0_ |= 0x00000001;
          } else {
            ensureTextIsMutable();
            text_.addAll(other.text_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureTextIsMutable();
                text_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList text_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureTextIsMutable() {
        if (!text_.isModifiable()) {
          text_ = new com.google.protobuf.LazyStringArrayList(text_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string text = 1;</code>
       * @return A list containing the text.
       */
      public com.google.protobuf.ProtocolStringList
          getTextList() {
        text_.makeImmutable();
        return text_;
      }
      /**
       * <code>repeated string text = 1;</code>
       * @return The count of text.
       */
      public int getTextCount() {
        return text_.size();
      }
      /**
       * <code>repeated string text = 1;</code>
       * @param index The index of the element to return.
       * @return The text at the given index.
       */
      public java.lang.String getText(int index) {
        return text_.get(index);
      }
      /**
       * <code>repeated string text = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the text at the given index.
       */
      public com.google.protobuf.ByteString
          getTextBytes(int index) {
        return text_.getByteString(index);
      }
      /**
       * <code>repeated string text = 1;</code>
       * @param index The index to set the value at.
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTextIsMutable();
        text_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       * @param value The text to add.
       * @return This builder for chaining.
       */
      public Builder addText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTextIsMutable();
        text_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       * @param values The text to add.
       * @return This builder for chaining.
       */
      public Builder addAllText(
          java.lang.Iterable<java.lang.String> values) {
        ensureTextIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, text_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       * @param value The bytes of the text to add.
       * @return This builder for chaining.
       */
      public Builder addTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureTextIsMutable();
        text_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tokenizeSerialize.TextList)
    }

    // @@protoc_insertion_point(class_scope:tokenizeSerialize.TextList)
    private static final phi3zh.common.Tokenize.TextList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new phi3zh.common.Tokenize.TextList();
    }

    public static phi3zh.common.Tokenize.TextList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextList>
        PARSER = new com.google.protobuf.AbstractParser<TextList>() {
      @java.lang.Override
      public TextList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TextList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public phi3zh.common.Tokenize.TextList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TokensOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tokenizeSerialize.Tokens)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 tokens = 1;</code>
     * @return A list containing the tokens.
     */
    java.util.List<java.lang.Integer> getTokensList();
    /**
     * <code>repeated int32 tokens = 1;</code>
     * @return The count of tokens.
     */
    int getTokensCount();
    /**
     * <code>repeated int32 tokens = 1;</code>
     * @param index The index of the element to return.
     * @return The tokens at the given index.
     */
    int getTokens(int index);
  }
  /**
   * Protobuf type {@code tokenizeSerialize.Tokens}
   */
  public static final class Tokens extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tokenizeSerialize.Tokens)
      TokensOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        Tokens.class.getName());
    }
    // Use Tokens.newBuilder() to construct.
    private Tokens(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Tokens() {
      tokens_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_Tokens_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_Tokens_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              phi3zh.common.Tokenize.Tokens.class, phi3zh.common.Tokenize.Tokens.Builder.class);
    }

    public static final int TOKENS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList tokens_ =
        emptyIntList();
    /**
     * <code>repeated int32 tokens = 1;</code>
     * @return A list containing the tokens.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getTokensList() {
      return tokens_;
    }
    /**
     * <code>repeated int32 tokens = 1;</code>
     * @return The count of tokens.
     */
    public int getTokensCount() {
      return tokens_.size();
    }
    /**
     * <code>repeated int32 tokens = 1;</code>
     * @param index The index of the element to return.
     * @return The tokens at the given index.
     */
    public int getTokens(int index) {
      return tokens_.getInt(index);
    }
    private int tokensMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getTokensList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(tokensMemoizedSerializedSize);
      }
      for (int i = 0; i < tokens_.size(); i++) {
        output.writeInt32NoTag(tokens_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < tokens_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(tokens_.getInt(i));
        }
        size += dataSize;
        if (!getTokensList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        tokensMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof phi3zh.common.Tokenize.Tokens)) {
        return super.equals(obj);
      }
      phi3zh.common.Tokenize.Tokens other = (phi3zh.common.Tokenize.Tokens) obj;

      if (!getTokensList()
          .equals(other.getTokensList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTokensCount() > 0) {
        hash = (37 * hash) + TOKENS_FIELD_NUMBER;
        hash = (53 * hash) + getTokensList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static phi3zh.common.Tokenize.Tokens parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phi3zh.common.Tokenize.Tokens parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.Tokens parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phi3zh.common.Tokenize.Tokens parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.Tokens parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phi3zh.common.Tokenize.Tokens parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.Tokens parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static phi3zh.common.Tokenize.Tokens parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static phi3zh.common.Tokenize.Tokens parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static phi3zh.common.Tokenize.Tokens parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.Tokens parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static phi3zh.common.Tokenize.Tokens parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(phi3zh.common.Tokenize.Tokens prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tokenizeSerialize.Tokens}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tokenizeSerialize.Tokens)
        phi3zh.common.Tokenize.TokensOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_Tokens_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_Tokens_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                phi3zh.common.Tokenize.Tokens.class, phi3zh.common.Tokenize.Tokens.Builder.class);
      }

      // Construct using phi3zh.common.Tokenize.Tokens.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        tokens_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_Tokens_descriptor;
      }

      @java.lang.Override
      public phi3zh.common.Tokenize.Tokens getDefaultInstanceForType() {
        return phi3zh.common.Tokenize.Tokens.getDefaultInstance();
      }

      @java.lang.Override
      public phi3zh.common.Tokenize.Tokens build() {
        phi3zh.common.Tokenize.Tokens result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public phi3zh.common.Tokenize.Tokens buildPartial() {
        phi3zh.common.Tokenize.Tokens result = new phi3zh.common.Tokenize.Tokens(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(phi3zh.common.Tokenize.Tokens result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          tokens_.makeImmutable();
          result.tokens_ = tokens_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof phi3zh.common.Tokenize.Tokens) {
          return mergeFrom((phi3zh.common.Tokenize.Tokens)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(phi3zh.common.Tokenize.Tokens other) {
        if (other == phi3zh.common.Tokenize.Tokens.getDefaultInstance()) return this;
        if (!other.tokens_.isEmpty()) {
          if (tokens_.isEmpty()) {
            tokens_ = other.tokens_;
            tokens_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureTokensIsMutable();
            tokens_.addAll(other.tokens_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureTokensIsMutable();
                tokens_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureTokensIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  tokens_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList tokens_ = emptyIntList();
      private void ensureTokensIsMutable() {
        if (!tokens_.isModifiable()) {
          tokens_ = makeMutableCopy(tokens_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated int32 tokens = 1;</code>
       * @return A list containing the tokens.
       */
      public java.util.List<java.lang.Integer>
          getTokensList() {
        tokens_.makeImmutable();
        return tokens_;
      }
      /**
       * <code>repeated int32 tokens = 1;</code>
       * @return The count of tokens.
       */
      public int getTokensCount() {
        return tokens_.size();
      }
      /**
       * <code>repeated int32 tokens = 1;</code>
       * @param index The index of the element to return.
       * @return The tokens at the given index.
       */
      public int getTokens(int index) {
        return tokens_.getInt(index);
      }
      /**
       * <code>repeated int32 tokens = 1;</code>
       * @param index The index to set the value at.
       * @param value The tokens to set.
       * @return This builder for chaining.
       */
      public Builder setTokens(
          int index, int value) {

        ensureTokensIsMutable();
        tokens_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 tokens = 1;</code>
       * @param value The tokens to add.
       * @return This builder for chaining.
       */
      public Builder addTokens(int value) {

        ensureTokensIsMutable();
        tokens_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 tokens = 1;</code>
       * @param values The tokens to add.
       * @return This builder for chaining.
       */
      public Builder addAllTokens(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTokensIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tokens_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 tokens = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTokens() {
        tokens_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tokenizeSerialize.Tokens)
    }

    // @@protoc_insertion_point(class_scope:tokenizeSerialize.Tokens)
    private static final phi3zh.common.Tokenize.Tokens DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new phi3zh.common.Tokenize.Tokens();
    }

    public static phi3zh.common.Tokenize.Tokens getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tokens>
        PARSER = new com.google.protobuf.AbstractParser<Tokens>() {
      @java.lang.Override
      public Tokens parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Tokens> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tokens> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public phi3zh.common.Tokenize.Tokens getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TokenListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tokenizeSerialize.TokenList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    java.util.List<phi3zh.common.Tokenize.Tokens> 
        getListList();
    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    phi3zh.common.Tokenize.Tokens getList(int index);
    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    java.util.List<? extends phi3zh.common.Tokenize.TokensOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    phi3zh.common.Tokenize.TokensOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tokenizeSerialize.TokenList}
   */
  public static final class TokenList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tokenizeSerialize.TokenList)
      TokenListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        TokenList.class.getName());
    }
    // Use TokenList.newBuilder() to construct.
    private TokenList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TokenList() {
      list_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TokenList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TokenList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              phi3zh.common.Tokenize.TokenList.class, phi3zh.common.Tokenize.TokenList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<phi3zh.common.Tokenize.Tokens> list_;
    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<phi3zh.common.Tokenize.Tokens> getListList() {
      return list_;
    }
    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends phi3zh.common.Tokenize.TokensOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    @java.lang.Override
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    @java.lang.Override
    public phi3zh.common.Tokenize.Tokens getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
     */
    @java.lang.Override
    public phi3zh.common.Tokenize.TokensOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof phi3zh.common.Tokenize.TokenList)) {
        return super.equals(obj);
      }
      phi3zh.common.Tokenize.TokenList other = (phi3zh.common.Tokenize.TokenList) obj;

      if (!getListList()
          .equals(other.getListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static phi3zh.common.Tokenize.TokenList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phi3zh.common.Tokenize.TokenList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.TokenList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phi3zh.common.Tokenize.TokenList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.TokenList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phi3zh.common.Tokenize.TokenList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.TokenList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static phi3zh.common.Tokenize.TokenList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static phi3zh.common.Tokenize.TokenList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static phi3zh.common.Tokenize.TokenList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static phi3zh.common.Tokenize.TokenList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static phi3zh.common.Tokenize.TokenList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(phi3zh.common.Tokenize.TokenList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tokenizeSerialize.TokenList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tokenizeSerialize.TokenList)
        phi3zh.common.Tokenize.TokenListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TokenList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TokenList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                phi3zh.common.Tokenize.TokenList.class, phi3zh.common.Tokenize.TokenList.Builder.class);
      }

      // Construct using phi3zh.common.Tokenize.TokenList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
        } else {
          list_ = null;
          listBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return phi3zh.common.Tokenize.internal_static_tokenizeSerialize_TokenList_descriptor;
      }

      @java.lang.Override
      public phi3zh.common.Tokenize.TokenList getDefaultInstanceForType() {
        return phi3zh.common.Tokenize.TokenList.getDefaultInstance();
      }

      @java.lang.Override
      public phi3zh.common.Tokenize.TokenList build() {
        phi3zh.common.Tokenize.TokenList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public phi3zh.common.Tokenize.TokenList buildPartial() {
        phi3zh.common.Tokenize.TokenList result = new phi3zh.common.Tokenize.TokenList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(phi3zh.common.Tokenize.TokenList result) {
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
      }

      private void buildPartial0(phi3zh.common.Tokenize.TokenList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof phi3zh.common.Tokenize.TokenList) {
          return mergeFrom((phi3zh.common.Tokenize.TokenList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(phi3zh.common.Tokenize.TokenList other) {
        if (other == phi3zh.common.Tokenize.TokenList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                phi3zh.common.Tokenize.Tokens m =
                    input.readMessage(
                        phi3zh.common.Tokenize.Tokens.parser(),
                        extensionRegistry);
                if (listBuilder_ == null) {
                  ensureListIsMutable();
                  list_.add(m);
                } else {
                  listBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<phi3zh.common.Tokenize.Tokens> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<phi3zh.common.Tokenize.Tokens>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          phi3zh.common.Tokenize.Tokens, phi3zh.common.Tokenize.Tokens.Builder, phi3zh.common.Tokenize.TokensOrBuilder> listBuilder_;

      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public java.util.List<phi3zh.common.Tokenize.Tokens> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public phi3zh.common.Tokenize.Tokens getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public Builder setList(
          int index, phi3zh.common.Tokenize.Tokens value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public Builder setList(
          int index, phi3zh.common.Tokenize.Tokens.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public Builder addList(phi3zh.common.Tokenize.Tokens value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public Builder addList(
          int index, phi3zh.common.Tokenize.Tokens value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public Builder addList(
          phi3zh.common.Tokenize.Tokens.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public Builder addList(
          int index, phi3zh.common.Tokenize.Tokens.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends phi3zh.common.Tokenize.Tokens> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public phi3zh.common.Tokenize.Tokens.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public phi3zh.common.Tokenize.TokensOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public java.util.List<? extends phi3zh.common.Tokenize.TokensOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public phi3zh.common.Tokenize.Tokens.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            phi3zh.common.Tokenize.Tokens.getDefaultInstance());
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public phi3zh.common.Tokenize.Tokens.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, phi3zh.common.Tokenize.Tokens.getDefaultInstance());
      }
      /**
       * <code>repeated .tokenizeSerialize.Tokens list = 1;</code>
       */
      public java.util.List<phi3zh.common.Tokenize.Tokens.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          phi3zh.common.Tokenize.Tokens, phi3zh.common.Tokenize.Tokens.Builder, phi3zh.common.Tokenize.TokensOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              phi3zh.common.Tokenize.Tokens, phi3zh.common.Tokenize.Tokens.Builder, phi3zh.common.Tokenize.TokensOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tokenizeSerialize.TokenList)
    }

    // @@protoc_insertion_point(class_scope:tokenizeSerialize.TokenList)
    private static final phi3zh.common.Tokenize.TokenList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new phi3zh.common.Tokenize.TokenList();
    }

    public static phi3zh.common.Tokenize.TokenList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenList>
        PARSER = new com.google.protobuf.AbstractParser<TokenList>() {
      @java.lang.Override
      public TokenList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TokenList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public phi3zh.common.Tokenize.TokenList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tokenizeSerialize_TextList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tokenizeSerialize_TextList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tokenizeSerialize_Tokens_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tokenizeSerialize_Tokens_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tokenizeSerialize_TokenList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tokenizeSerialize_TokenList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/resources/tokenize.proto\022\021tok" +
      "enizeSerialize\"\030\n\010TextList\022\014\n\004text\030\001 \003(\t" +
      "\"\030\n\006Tokens\022\016\n\006tokens\030\001 \003(\005\"4\n\tTokenList\022" +
      "\'\n\004list\030\001 \003(\0132\031.tokenizeSerialize.Tokens" +
      "B\017\n\rphi3zh.commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tokenizeSerialize_TextList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tokenizeSerialize_TextList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tokenizeSerialize_TextList_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_tokenizeSerialize_Tokens_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tokenizeSerialize_Tokens_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tokenizeSerialize_Tokens_descriptor,
        new java.lang.String[] { "Tokens", });
    internal_static_tokenizeSerialize_TokenList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tokenizeSerialize_TokenList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tokenizeSerialize_TokenList_descriptor,
        new java.lang.String[] { "List", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
